### ISSUE TITLE
Cucumber-pro-ruby makes aruba-builds fail with cucumber 2

### ISSUE THREAD

**Issue by maxmeyer** [cucumber-ltd/cucumber-pro-ruby#4]
https://travis-ci.org/cucumber/aruba/jobs/62441359

Can anyone fix this? :smile: Thanks a lot.

```
`Cucumber::Ast` no longer exists. These classes have moved into the `Cucumber::Core::Ast` namespace, but may not have the same API. (RuntimeError)
/home/travis/.rvm/gems/ruby-2.1.5/gems/cucumber-2.0.0/lib/cucumber/ast.rb:10:in `const_missing'
/home/travis/.rvm/gems/ruby-2.1.5/gems/cucumber-pro-0.0.17/lib/cucumber/pro/formatter.rb:26:in `after_feature_element'
/home/travis/.rvm/gems/ruby-2.1.5/gems/cucumber-2.0.0/lib/cucumber/formatter/ignore_missing_messages.rb:10:in `method_missing'
/home/travis/.rvm/gems/ruby-2.1.5/gems/cucumber-2.0.0/lib/cucumber/formatter/legacy_api/adapter.rb:549:in `after'
/home/travis/.rvm/gems/ruby-2.1.5/gems/cucumber-2.0.0/lib/cucumber/formatter/legacy_api/adapter.rb:539:in `after_test_case'
/home/travis/.rvm/gems/ruby-2.1.5/gems/cucumber-2.0.0/lib/cucumber/formatter/legacy_api/adapter.rb:252:in `after_test_case'
/home/travis/.rvm/gems/ruby-2.1.5/gems/cucumber-2.0.0/lib/cucumber/formatter/legacy_api/adapter.rb:85:in `after_test_case'
/home/travis/.rvm/gems/ruby-2.1.5/gems/cucumber-2.0.0/lib/cucumber/formatter/legacy_api/adapter.rb:37:in `after_test_case'
/home/travis/.rvm/gems/ruby-2.1.5/gems/cucumber-2.0.0/lib/cucumber/formatter/fanout.rb:16:in `block in method_missing'
/home/travis/.rvm/gems/ruby-2.1.5/gems/cucumber-2.0.0/lib/cucumber/formatter/fanout.rb:15:in `each'
/home/travis/.rvm/gems/ruby-2.1.5/gems/cucumber-2.0.0/lib/cucumber/formatter/fanout.rb:15:in `method_missing'
```

**Comment by mattwynne** [comment]
We need to update the cucumber-pro plugin to work with Cucumber 2.0. For now, let's just disable it in our build.

**Comment by maxmeyer** [comment]
Ok.
